=== PI-Portal/pi_portal/pi_portal/schema/config_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "description": "Pi Portal v1.6 Config File Schema",
    "type": "object",
    "properties":
        {
             "AWS_ACCESS_KEY_ID":
                {
                    "type": "string",
                    "description": "The AWS access key credential with write access to the bucket."
                },
            "AWS_SECRET_ACCESS_KEY":
                {
                    "type": "string",
                    "description": "The AWS access secret key credential with write access to the bucket."
                },
            "AWS_S3_BUCKETS": {
                "type": "object",
                "properties": {
                    "LOGS": {
                        "type": "string",
                        "description": "The name of the AWS S3 bucket to upload archived logs to."
                    },
                    "VIDEOS":{
                        "type": "string",
                        "description": "The name of the AWS S3 bucket to upload captured videos to."
                    }
                },
                "required": [
                    "LOGS",
                    "VIDEOS"
                ]
            },
            "LOGZ_IO_CODE":
                {
                    "type": "string",
                    "description": "A code generated by log.io, which will be injected into streamed logs to identify your account."
                },
            "SLACK_APP_SIGNING_SECRET":
                {
                    "type": "string",
                    "description": "The secret value generated by Slack to validate messages from your bot."
                },
            "SLACK_APP_TOKEN":
                {
                    "type": "string",
                    "description": "The app token generated by Slack to allow your bot use websockets."
                },
            "SLACK_BOT_TOKEN":
                {
                    "type": "string",
                    "description": "The token generated by Slack when you created a bot app."
                },
            "SLACK_CHANNEL":
                {
                    "type": "string",
                    "description": "The plain human readable name of the Slack channel where messages should be posted."
                },
            "SLACK_CHANNEL_ID":
                {
                    "type": "string",
                    "description": "The ID of the slack channel.  Can be found at the bottom of the dialogue for 'View Channel Details > About'."
                },
            "CONTACT_SWITCHES":
                {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "NAME": {
                                "type": "string",
                                "description": "The name of the switch as it will appear in notifications and logs (ie. Front Door)."
                            },
                            "GPIO": {
                                "type": "number",
                                "description": "The GPIO number this contact switch connects to."
                            }
                        },
                        "required": ["NAME", "GPIO"]
                    }
                },
            "TEMPERATURE_SENSORS": {
                "description": "Configured temperature sensors",
                "type": "object",
                "properties": {
                    "DHT11_SENSORS": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "NAME": {
                                    "type": "string",
                                    "description": "The name of the sensor as it will appear in notifications and logs (ie. Living Room)."
                                },
                                "GPIO": {
                                    "type": "number",
                                    "description": "The GPIO number this DHT11 sensor connects to."
                                }
                            },
                            "required": [
                                "NAME",
                                "GPIO"
                            ]
                        }
                    }
                },
                "required": [
                    "DHT11"
                ]
            }

        },
    "required": ["AWS_ACCESS_KEY_ID", "AWS_SECRET_ACCESS_KEY", "AWS_S3_BUCKETS", "CONTACT_SWITCHES", "LOGZ_IO_CODE", "SLACK_APP_SIGNING_SECRET", "SLACK_APP_TOKEN", "SLACK_BOT_TOKEN", "SLACK_CHANNEL", "SLACK_CHANNEL_ID", "TEMPERATURE_SENSORS"]
}

=== PI-Portal/pi_portal/config.json
{
    "AWS_ACCESS_KEY_ID": "... AWS key with write access to buckets ...",
    "AWS_SECRET_ACCESS_KEY": "... AWS secret key with write access buckets ...",
    "AWS_S3_BUCKETS": {
        "LOGS": "... s3 logs bucket name ...",
        "VIDEOS": "... s3 video bucket name ..."
    },
    "CONTACT_SWITCHES": [
        {
            "NAME": "... name and pin-out of a GPIO switch...",
            "GPIO": 12
        }
    ],
    "LOGZ_IO_CODE": "... logz io's logger code ...",
    "SLACK_APP_SIGNING_SECRET": "... secret value from slack to validate bot messages ...",
    "SLACK_APP_TOKEN": "... token from slack to allow app to use websockets ...",
    "SLACK_BOT_TOKEN": "... token from slack...",
    "SLACK_CHANNEL": "... proper name of slack channel ...",
    "SLACK_CHANNEL_ID": ".. slack's ID for the channel ...",
    "TEMPERATURE_SENSORS": {
        "DHT11": [
            {
                "NAME": "... name and pin-out of a GPIO with a DHT11 connected ...",
                "GPIO": 4
            }
        ]
    }
}
